MAX_TOKEN_PASSAGE_TO_USE_AS_IT_IS=500
ABSOLUTE_MAX_TOKEN_LIMIT=512

EMBDEEING_MODEL="intfloat/multilingual-e5-large"
LLM_MODEL="meta-llama/Llama-3.3-70B-Instruct"
DB_CONFIG_PATH="configs/database.yaml"

GOOGLE_APIS_CSV="extra/google_apis.csv"


COPIER_GOOGLE_MODEL="gemini-2.0-flash"
COPIER_MAX_ALLOWED_RPD=1480
COPIER_MAX_ALLOWED_RPM=12

REWRITER_GOOGLE_MODEL="gemini-2.5-flash-preview-05-20"
REWRITER_MAX_ALLOWED_RPD=480
REWRITER_MAX_ALLOWED_RPM=8
